### ISSUE TITLE
What is this module meant for ? 

### ISSUE THREAD

**Issue by gauravsaini** [watson/dns-equal#1]
So as I can see what this module does is nothing other than comparing two strings. 
In what circumstances would you even need such a module ?

**Comment by watson** [comment]
The module is meant for comparing two domain names to see if they are the same.

If you read the source code, you'd see that it does more than a simple string comparison. To know how to compare domains a developer would need to read [RFC 1035](https://tools.ietf.org/html/rfc1035), so by using this module, you don't have to read the RFC or to implement the algorithm your self. This makes it easier to be RFC 1035 complaint.
